### ISSUE TITLE
Setting your reportDir as a directory and not a discrete filePath causes errors

### ISSUE THREAD

**Issue by aaron-goff** [blakyaks/azure-pipeline-html-reports#2]
This issue is essentially the same as https://github.com/JakubRumpca/azure-pipeline-html-report/issues/11.

If you set your `reportDir` as a directory, you end up with an error.

At the very least, if you don't plan on fixing the behavior, I think modifying the variable name would be appropriate - it doesn't want a directory, it wants a file.

**Comment by blakyaks** [comment]
Thanks @aaron-goff, wasn't aware of this issue as we only use for single files usually. We've updated so you can use either file or directory paths now and have updated the extension in the Marketplace to v1.2.0.
