### ISSUE TITLE
[Improvement] - Attaching multiple files have the same tab name

### ISSUE THREAD

**Issue by aaron-goff** [blakyaks/azure-pipeline-html-reports#4]
#3 works great (I really appreciate the fast turnaround on that 😄 ) - it now correctly finds multiple files if you pass in a directory. However, if you do add multiple reports, it displays them all with the same name.
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/4774dcb2-2b89-4ee7-9cdf-1fe31e39da2a">

An improvement would be to _somehow_ allow passing in multiple names, or possibly just making the tab name the file name.

Rough idea for the latter:

```javascript
const isDir = statSync(reportInputPath).isDirectory();
...
            const attachmentProperties = {
                name: generateAttachmentName(basename(file), isDir),
                type: 'report-html',
                path: file
            };
...

function generateAttachmentName(fileName, isDirectory) {
    const jobName = dashify(tl.getVariable('Agent.JobName'));
    const stageName = dashify(tl.getVariable('System.StageDisplayName'));
    const stageAttempt = tl.getVariable('System.StageAttempt');
    let tabName;
    if (isDirectory) {
      tabName = fileName.split('/').at(-1);
    } else {
      tabName = tl.getInput('tabName', false) || 'Html-Report';
    }
    return `${tabName}.${jobName}.${stageName}.${stageAttempt}.${fileName}`;
}
```
Although, to be honest, I'm not 100% on how the attachment name works.

**Comment by blakyaks** [comment]
Filename based report tabs now enabled by default, Marketplace extension bumped to v1.2.1
